### ISSUE TITLE
Reveal Template broken with FF

### ISSUE THREAD

**Issue by atwellpub** [inboundnow/landing-pages#163]
Center button is off center on FF but works with Chrome. 
http://support.inboundnow.com/support/topic/reveal-template-improper-display/

**Comment by DavidWells** [comment]
firefox needs 

```css
.btn {
top:78%;
}
```

How do you target css to firefox exclusively?

**Comment by atwellpub** [comment]
https://css-tricks.com/snippets/css/css-hacks-targeting-firefox/ Looks like there is a way.

**Comment by DavidWells** [comment]
Nah doesn't work. Lets just refund or give them other template

**Comment by atwellpub** [comment]
What about the template being on market?

We may could do some PHP useragent inline css prints?

Refunded.

**Comment by atwellpub** [comment]
Added this to the index.php and updated demo.inboundnow.com

```
<?php
/**
*  adjustment for firefox
*/

if (stristr( $_SERVER['HTTP_USER_AGENT'] , 'firefox' ) ) {
	echo '.btn {
		top:78% !important;
	}';
}
?>
```
