### ISSUE TITLE
What updates landing page impressions?

### ISSUE THREAD

**Issue by DavidWells** [inboundnow/landing-pages#166]
When pro is active, landing page impressions do not record.

What ajax runs landing page impressions. What PHP

**Comment by atwellpub** [comment]
I am not showing a repeatable error with only Pro installed. Will you pull again and verify?
http://screencast.com/t/gekbZqhr

https://github.com/inboundnow/landing-pages/blob/e4e7d4fe31148620a02643af62bd1f747bda6b95/shared/classes/class.ajax.php#L60
https://github.com/inboundnow/landing-pages/blob/4c28b958fe684d377fa91b4cfee7f0e66a362b71/modules/module.ab-testing.php#L931 (this location will change with the refactoring)
