### ISSUE TITLE
Errors on activtion

### ISSUE THREAD

**Issue by DavidWells** [inboundnow/landing-pages#169]
Warning: include_once(classes/class.load-extensions.php): failed to open stream: No such file or directory in /Users/davidwells/Dropbox/Sites/WP.dev/wp-content/plugins/landing-pages/landing-pages.php on line 77

Warning: include_once(): Failed opening 'classes/class.load-extensions.php' for inclusion (include_path='.:/Applications/MAMP/bin/php/php5.4.39/lib/php') in /Users/davidwells/Dropbox/Sites/WP.dev/wp-content/plugins/landing-pages/landing-pages.php on line 77

Warning: Cannot modify header information - headers already sent by (output started at /Users/davidwells/Dropbox/Sites/WP.dev/wp-content/plugins/landing-pages/landing-pages.php:77) in /Users/davidwells/Dropbox/Sites/WP.dev/wp-includes/pluggable.php on line 1196

![error](https://cloud.githubusercontent.com/assets/532272/8173032/ac8424a2-137c-11e5-9788-68183f548494.png)

**Comment by atwellpub** [comment]
https://github.com/inboundnow/landing-pages/issues/168
