### ISSUE TITLE
Remove p,a,c,k,e,r code

### ISSUE THREAD

**Issue by atwellpub** [inboundnow/landing-pages#171]
Mika from WordPress.org is charging us to replace the following:

http://plugins.svn.wordpress.org/landing-pages/tags/1.8.8/libraries/shareme/sharrre/jquery.sharrre-1.3.3.min.js 

Her explanation:

`
2) p,a,c,k,e,r code isn't permitted
Minifying is fine, obfuscating is not.
`

Assigning you David because you have better awareness of this bit of code and are the best candidate to design a solution.

**Comment by atwellpub** [comment]
David did you address this one? When committing you can add the URL of the issue to the commit and it will automatically tag the issue with the commit.

**Comment by DavidWells** [comment]
this is gone. I updated the lib
