### ISSUE TITLE
Force flush of permalinks for all people. #170

### ISSUE THREAD

**Issue by DavidWells** [inboundnow/landing-pages#172]
https://github.com/inboundnow/landing-pages/commit/95a58186521c25f774dd7513534e078cb9be0430

Do you see any potential issues for this?

Also open to idea on where to place this code.

We also need to implement in such a way that it runs for LP, CTA, Emails etc separately

**Comment by atwellpub** [comment]
CTA: 
https://github.com/inboundnow/cta/blob/master/classes/class.activation.php#L32

Landing Pages:
https://github.com/inboundnow/landing-pages/blob/master/classes/class.activation.php#L32

Mailer:
https://github.com/inboundnow/inbound-mailer/blob/master/classes/class.activation.php#L32

Even with the activation flushes if the user has their default permlink setting set then some of our permalinks will not work. I am adding prompts to encourage users to update their permalink settings if set to default.
