### ISSUE TITLE
Updated Extensions + get templates in admin menu 

### ISSUE THREAD

**Issue by DavidWells** [inboundnow/landing-pages#173]
Reformatted store to a class and am saving user_meta to show store once they opt in.

Can you test: 

http://wpdev.dev/wp-admin/edit.php?post_type=landing-page&page=lp_store

You should see prompt first, then once you verify to show store, refresh the page and the prompt should vanish

**Comment by atwellpub** [comment]
It worked on accept, but on refresh I am still prompted. Looks good. Like the orange highlight.

**Comment by atwellpub** [comment]
Just pulled and checked again and it's sticking.

**Comment by DavidWells** [comment]
Cool.

I think we need to make it a class in shared and abstract it for use in CTA
and leads for upsells as well
