### ISSUE TITLE
Advanced Custom Fields Support

### ISSUE THREAD

**Issue by atwellpub** [inboundnow/landing-pages#174]
Advanced custom fields support for pro users is now in place. We are adding in ACF Lite support for free users. Right now the updates are in the 'Refactoring_metabox_modules' branch. 

Here's where we are keeping our demo ACF template at the moment:
https://bitbucket.org/inboundnow/acf-landing-page-example

* [x] ACF fields only show when acf template is selected
* [x] Variation storage seems to be saving and rendering correctly
* [x] Make one official template using ACF method.
* [x] Create official documentation on how to create templates using the ACF method for customers and outsourced labor. 
* [x] Restore Inbound Marketing button to ACF fields when lite is running

**Comment by atwellpub** [comment]
@DavidWells @daprela 

Hey guys, would you create a landing page with countdown lander with 3 variations? 

I'm about to push the Countdown ACF version and want to see how it fits with the legacy version data and if there are any issues.

**Comment by DavidWells** [comment]
ok I have it created

**Comment by atwellpub** [comment]
I think we are going to have to include acf in landing pages/shared.

**Comment by DavidWells** [comment]
yes acf normal would go in /shared/.
http://plugins.svn.wordpress.org/advanced-custom-fields/trunk/ minus assets
not needed like screenshots

When inbound-pro gets ran through it's production build, /shared/acf normal
will be removed/replaced with acf pro files

One concern I have is conflicts with different versions of ACF normal/pro
out there... Not sure if this will happen or not

**Comment by atwellpub** [comment]
ok pushed.

**Comment by atwellpub** [comment]
More handling for acf + countdown. Still running tests. Will pick up …
…tomorrow.

https://github.com/inboundnow/landing-pages/commit/0b8ddb6db8f374c081d15d6572fedd39971394d3

**Comment by atwellpub** [comment]
Issue with Landing Pages ACF, in converting to ACF we are going to need to load the config.php files in the front end. 

I worry about performance issues, but we can't use ACF return value formatting without the fields being predefined by ACF on the front end. 

Which means for example, we might want stored images to return the URL but instead all ACF will return is the media attachment ID, so we'd have to apply extra PHP handling to get the image URL from the attachment ID. Like this:

https://github.com/inboundnow/landing-pages/blob/master/templates/countdown-lander/index.php#L42-L45

While values from our legacy system are already stored in URL format. 

This is just the issue I have run into with images, without a work around besides loading template files in the frontend which seems like it might affect load times....

**Comment by DavidWells** [comment]
Why does ACF need to load in frontend? What part?

**Comment by atwellpub** [comment]
No, I was wrong it's not necessary, I was mistaken. But on ACF templates when we will need to load the config.php file as a php include.

**Comment by atwellpub** [comment]
The ACF field definitions part; the PHP insert.

**Comment by atwellpub** [comment]
@DavidWells @daprela 

Notice, when defining field groups in config.php files for our free version we have to use:

register_field_group

instead of:

acf_add_local_field_group

https://github.com/elliotcondon/acf/issues/412

**Comment by atwellpub** [comment]
@DavidWells 

It also looks like the 'Marketing' & 'Add Media' buttons dissapear when a user is not using ACF Pro. 


![](http://content.screencast.com/users/adbox/folders/Jing/media/7b3e5246-83c3-4cb6-8a0b-480a6205bef0/2015-08-24_1959.png)
