### ISSUE TITLE
Show impressions/conversions on all post types

### ISSUE THREAD

**Issue by atwellpub** [inboundnow/landing-pages#177]
* Optional?
* Pro?

http://support.inboundnow.com/support/topic/overview-of-inbound-statistics-for-each-page/#post-115877

**Comment by DavidWells** [comment]
This should roll into a bigger analytics picture.

Namely having dates associated with the numbers and/or google analytics
stats.

The guy can run meta queries right now to pull out the individual pieces of
data.

Perhaps it can be a single api endpoint:
site.com/inbound-api/analytics/PAGEID?apikey=hehehehe <= GET request and it
returns the stats.

I don't want to put too much effort into our own API on the wordpress side
before the WP JSON api rolls out ( I hear in dec )
