### ISSUE TITLE
Question about inbound_build_template_options() function in utils module

### ISSUE THREAD

**Issue by atwellpub** [inboundnow/landing-pages#196]
Hey David, what does this do? Do we want to keep it?

https://github.com/inboundnow/landing-pages/blob/master/modules/module.utils.php#L240-L273

**Comment by DavidWells** [comment]
It generates the options needed for the template from its config file. So you can copy/paste the variables for use in template index.php

It's for dev ux.

We will need to revamp for ACF. It can be removed for now

**Comment by atwellpub** [comment]
ok great, what about this one?

https://github.com/inboundnow/landing-pages/blob/master/modules/module.utils.php#L214-L238

**Comment by DavidWells** [comment]
Those can be deleted too.

They were for adding a class to the body of the page.

They only work in some scenarios
