### ISSUE TITLE
Visual Editor broken from refactor:

### ISSUE THREAD

**Issue by DavidWells** [inboundnow/landing-pages#197]
Something is wrong with the visual customizer.

It's like its missing enqueued files and the frontend=true/false is not working correctly to load the correct JS and CSS needed for the customizer to function

http://www.screencast.com/t/RmtC3QTsPww

Did you change the enqueue mechanisms?

**Comment by atwellpub** [comment]
I'm having a hard time figuring out how I lost this / how to restore it. I'd think that somehow, on the save page's reload, it reloads with the frontend=true param, but I can't find in the old code where we were doing this.
