### ISSUE TITLE
Shortcode files broken

### ISSUE THREAD

**Issue by DavidWells** [inboundnow/landing-pages#201]
https://github.com/inboundnow/landing-pages/blob/master/shared/shortcodes/shortcodes/forms.php is empty and causing fatals on install.

Also looks like  https://github.com/inboundnow/landing-pages/blob/master/shared/shortcodes/shortcodes/ are empty and causing issues as well

Can you restore whatever changes you made to them?

**Comment by DavidWells** [comment]
All the files were changed to binary https://github.com/inboundnow/landing-pages/blob/3156dc11446b5229972cfd1962709dbff233657a/shared/shortcodes/shortcodes/video.php

**Comment by atwellpub** [comment]
restored. Not sure what happend. I did have a crash in the middle of a gulp task. Maybe that is what did it.
