### ISSUE TITLE
Add back phantomjs test path to override 1.9.1 user files

### ISSUE THREAD

**Issue by DavidWells** [inboundnow/landing-pages#205]
It was recommended to override the http://plugins.svn.wordpress.org/landing-pages/tags/1.9.1/tests/phantomjs/server.php with an empty file like so https://github.com/inboundnow/landing-pages/commit/cd4b16ad04a1a85c8ca23b70b4b716e8924f7914

For the next couple releases, we need to temporary add back the /tests/phantomjs/server.php path with server.php as a blank PHP file. 

Can you make this quick change in live /trunk and /1.9.2 tag in WP SVN?

**Comment by DavidWells** [comment]
I tried but my SVN client is a p.o.s =(

**Comment by atwellpub** [comment]
server.php isn't leveraged by anything so removing it out right should not need to be included I don;'t think. We should just be able to remove it all together.

**Comment by atwellpub** [comment]
Ok I see. 

I added it back in.
