### ISSUE TITLE
wp_head hook not firing

### ISSUE THREAD

**Issue by DavidWells** [inboundnow/landing-pages#207]
https://github.com/inboundnow/landing-pages/blob/master/classes/class.post-type.landing-page.php#L645 is no longer firing and I can't figure out why

URL params are no longer cleaning.

I am going to update the URL cleaning functionality to only remove the lp-variation-id but this javascript won't load in the wp_head from this class for some reason.

Any ideas why?

**Comment by atwellpub** [comment]
Fixed, had an issue with the code conditional.
