### ISSUE TITLE
Do we use 'landing_page_header_script' action?

### ISSUE THREAD

**Issue by DavidWells** [inboundnow/landing-pages#208]
https://github.com/inboundnow/landing-pages/blob/a623c40d3c238176d14e6b34b51b7c2a828a6eeb/classes/class.post-type.landing-page.php#L652

**Comment by atwellpub** [comment]
Doesn't look like it. I left it in there because it was in prior. But most templates call wp_head which is an equivalent.

**Comment by atwellpub** [comment]
Removed it.
