### ISSUE TITLE
Datepicker format

### ISSUE THREAD

**Issue by DavidWells** [inboundnow/landing-pages#210]
Does the date format need to be like this? https://github.com/inboundnow/landing-pages/blob/master/templates/countdown-lander/config.php#L115-L116

can't we do the standard M/dd/Y ?

Is it reading very strangely http://www.screencast.com/t/xHnF6xU5zipA and it looks like I'm unable to change the year

**Comment by atwellpub** [comment]
@daprela What do you think? 

I think we can change it to the M/dd/Y. Will wait on Guilio's opinion before I change it. 

On the index.php side we break down the date string and rebuild it. So Whichever way we chose should work. Would need to test to make sure.
