### ISSUE TITLE
[acf] Dropcap conversion

### ISSUE THREAD

**Issue by atwellpub** [inboundnow/landing-pages#211]

**Comment by atwellpub** [comment]
* [ ] Create 3 variations and test

**Comment by DavidWells** [comment]
Looks like the image ACF field is missing the default values: http://www.screencast.com/t/GMgkwxwExZnB

Also the old template options area is on the edit screen with some php errors: http://www.screencast.com/t/oBqcKqM9ECE

```
Notice: Undefined index: settings in /Users/davidwells/Dropbox/Sites/WP.dev/wp-content/plugins/landing-pages/classes/class.metaboxes.php on line 874

Warning: Invalid argument supplied for foreach() in /Users/davidwells/Dropbox/Sites/WP.dev/wp-content/plugins/landing-pages/classes/class.metaboxes.php on line 919
```

**Comment by atwellpub** [comment]
Ok default image restored, couldn't repeat the undefined index issue maybe after the next pull you won't experience them.

**Comment by DavidWells** [comment]
B version was okay but my unsaved A version threw this in the content output:

http://www.screencast.com/t/JErPNq3R9wT

```
Warning: strpos() expects parameter 1 to be string, array given in /Users/davidwells/Dropbox/Sites/WP.dev/wp-includes/shortcodes.php on line 191

Warning: preg_match() expects parameter 2 to be string, array given in /Users/davidwells/Dropbox/Sites/WP.dev/wp-includes/shortcodes.php on line 202

Notice: Array to string conversion in /Users/davidwells/Dropbox/Sites/WP.dev/wp-content/plugins/landing-pages/templates/dropcap/index.php on line 108
Array
```

Have you seen this before?

**Comment by atwellpub** [comment]
I have but It shouldn't be showing in the latest version. Just making some changes now that might fix it:

**Comment by atwellpub** [comment]
* Conversion area not displaying.
* Pullet points not rendering correctly

**Comment by atwellpub** [comment]
@DavidWells I'm noticing a bullet point issue with the DropCap template. Do we have a strategy yet on addressing these? I've never really understood the issue.
