### ISSUE TITLE
Landing Page Preview Mode - Variation switching repair work

### ISSUE THREAD

**Issue by atwellpub** [inboundnow/landing-pages#213]
The variation switch buttons seem to have lost their styling over the course of refactoring. And they only show if variation A is being loaded. 

We can restore the feature or remove it. 

![](http://content.screencast.com/users/adbox/folders/Jing/media/4f391bf1-3c8e-42a2-9a50-b6e98eb65096/2015-08-27_1500.png)

**Comment by DavidWells** [comment]
Those were hosed. I'm removing this from functionality for now.

The preview window will be revamped someday but not right now
