### ISSUE TITLE
Ideas to clean up config.php for easier templating

### ISSUE THREAD

**Issue by DavidWells** [inboundnow/landing-pages#216]
Can we get rid of these config blocks: https://github.com/inboundnow/landing-pages/blob/53e214b8bcc036eb20531794637b24ba5111ec72/templates/half-and-half/config.php#L24-L40 ?

Also, did we ever use https://github.com/inboundnow/landing-pages/blob/53e214b8bcc036eb20531794637b24ba5111ec72/templates/half-and-half/config.php#L8 the custom hook? if not, lets kill it. It's confusing to even myself =P

Is there a way to clean up the actual config to just have the template info, then the register fields? ( here https://github.com/inboundnow/landing-pages/blob/53e214b8bcc036eb20531794637b24ba5111ec72/templates/half-and-half/config.php#L11-L21 )

Like instead of 
```php
$key = lp_get_parent_directory(dirname(__FILE__));
$lp_data[$key]['info'] =
array(
	'data_type' => 'template',
	'version' => "2.0.1",
	'label' => "Half and Half",
	'category' => '2 column layout',
	'demo' => 'http://demo.inboundnow.com/go/half-and-half-lander-preview/',
	'description'  => 'Half and Half is a template with two content areas on each side of the page. One side has your conversion area and the other your content on the page.' // template description
);
```

We just have:
```php
$config = array(
	'data_type' => 'template', // this data type seems redundant. Can we remove?
	'version' => "2.0.1",
	'label' => "Half and Half",
	'category' => '2 column layout',
	'demo' => 'http://demo.inboundnow.com/go/half-and-half-lander-preview/',
	'description'  => 'Half and Half is a template with two content areas on each side of the page'
);
// then acf register fields below
```

**Comment by atwellpub** [comment]
These:

https://github.com/inboundnow/landing-pages/blob/53e214b8bcc036eb20531794637b24ba5111ec72/templates/half-and-half/config.php#L24-L40

Yes we can if we build a special handler for ACF powered templates. It will take some careful research and implementation. We can't hide all these all together yet because of all the people with custom template builds.

**Comment by atwellpub** [comment]
@DavidWells 

Templates now, if powered by ACF, and marked here:
https://github.com/inboundnow/landing-pages/blob/feature/Template_conversions_to_acf/templates/countdown-lander/config.php#L24

Have the unused UI elements automatically removed instruction field automatically added.

See: 
https://github.com/inboundnow/landing-pages/commit/dcbe051c140836d964c2b0c6dd34c17b0f9eb37a

**Comment by DavidWells** [comment]
I like that the config is cleaner. Nice work.

**Comment by DavidWells** [comment]
do we need this?
https://github.com/inboundnow/landing-pages/blob/feature/Template_conversions_to_acf/templates/countdown-lander/config.php#L18
seems like overkill.

Maybe we can use that data_type to specify if the template is an ACF
template or not. Then we don't need the additional parameter on the config.

Like:

```php
$lp_data[$key]['info'] = array(
'data_type' => 'acf', // Template Data Type
'version' => "1.0.5", // Version Number
'label' => __( 'Countdown Lander' , 'landing-pages' ), // Nice Name
'category' => 'Countdown,1 column', // Template Category
'demo' => 'http://demo.inboundnow.com/go/countdown-lander/', // Demo Link
'description'  => __( 'Coundown Lander provides a simple sharp looking
countdown page.' , 'landing-pages' ), // template description
);
```
