### ISSUE TITLE
Standardize lp_get_parent_directory function

### ISSUE THREAD

**Issue by DavidWells** [inboundnow/landing-pages#220]
We need to make this a generic function that lives in /shared/ so all templates can use the same function to grab this path.

This is for standardizing templating across all post types

Something like: inbound_get_parent_directory will work

**Comment by atwellpub** [comment]
This is available now.

**Comment by atwellpub** [comment]
Looks like b/c landing page's config files are loaded before init and plugins_loaded the config.php cannot use methods defined in shared. Shared is loaded in plugins_loaded hook. I reversed my commit the changed lp_get_parent_directory to inbound_get_parent_directory.

**Comment by DavidWells** [comment]
We are going to need some functionality loaded from /shared/ before the plugins_loaded hook. 

Look like we might need to have a loader for stuff that needs to register quicker? 

like:

```php
trigger on init
private static function load_init_shared_files() {

}
trigger on plugins_loaded
private static function load_shared_files() {

}
```

**Comment by atwellpub** [comment]
Loading the template config data in init (init happens after plugins_loaded) has allowed us to convert lp_get_parent_directory to inbound_get_parent_directory().
