### ISSUE TITLE
[acf] Svtle 

### ISSUE THREAD

**Issue by atwellpub** [inboundnow/landing-pages#221]

**Comment by DavidWells** [comment]
Logo is broken from my previous unsaved versions: http://www.screencast.com/t/8YKMWAUlyErg

I tried grabbing the old value and using it like:

```php
$logo = get_field('svtle-logo', $post->ID, false); /* images need the false to disable formatting by ACF to be compatible with ACF 4 & 5 */

$old_logo = lp_get_value($post, $key, 'logo');
$final_logo = (isset($logo)) ? $logo : $old_logo;
```
but that didn't work either. Tried with and without acf pro activated. No luck.

It looks like this is happening on simple solid lite as well

**Comment by DavidWells** [comment]
NVM this conditional logic works to replace the logo I had:

```php
$logo = get_field('svtle-logo', $post->ID, false); 
$old_logo = lp_get_value($post, $key, 'logo');
$final_logo = ($logo) ? $logo : $old_logo;
```

**Comment by atwellpub** [comment]
Found the issue with legacy images not displaying. But now there is an issue with broken fontawesome icons in the default content. Are you experiencing this?

**Comment by DavidWells** [comment]
negative. I am seeing the default checkmarks on the fontawesome list.

This template looks good to me

**Comment by atwellpub** [comment]
Here is what I am seeing:

With ACF Pro:
* Default checkmarks show on first creation,
* They do not show after first save

With ACF Lite
* Default checkmarks do not show on first creation.
* Line breaks replace line returns.
* they do not show after save

**Comment by atwellpub** [comment]
Make sure Inbound Pro is off and ACF Pro is disabled.

**Comment by DavidWells** [comment]
What template?

**Comment by DavidWells** [comment]
There is no checkbox in Svtle. What do you mean? I see default toggle values

But yeah with acf lite when I save the default content is gets garbled like this: http://www.screencast.com/t/qQlmbEgXvf38

**Comment by DavidWells** [comment]
This code fixes the line break problem but the list item shortcode output is still missing.
```php
<?php
                 $content = wpautop($content);
                echo do_shortcode($content); ?>
```
This is the new page: http://www.screencast.com/t/rmnMhunZ

The list shortcode outputs a style block directly into the content (which is probably bad) https://github.com/inboundnow/landing-pages/blob/master/shared/shortcodes/inbound-shortcodes.php#L531-L562 

Other shortcodes work though. Probably need to move the CSS output of the shortcode elsewhere

**Comment by DavidWells** [comment]
@atwellpub do you know how to inline this css in wp_head/wp_footer instead? https://github.com/inboundnow/landing-pages/blob/master/shared/shortcodes/inbound-shortcodes.php#L532-L562

The CSS IDs need to be unique in case there are multiple lists with different icons in use

**Comment by atwellpub** [comment]
I am not quite sure I understand the question, but I just ran another round of tests and the shortcode list checkmarks seem to be populating correcty before save, after save, with acf pro on, and off.

**Comment by atwellpub** [comment]
Form below content on mobile is broke.
