### ISSUE TITLE
[acf] Three Column Lander

### ISSUE THREAD

**Issue by atwellpub** [inboundnow/landing-pages#222]

**Comment by DavidWells** [comment]
:+1: 

Can we start removing the $lp_data[$key]['settings'] from configs? https://github.com/inboundnow/landing-pages/commit/b58b6492b5bbc72d1a230bb18fd6ea06c354a4cd#diff-46ff2b60bff3e8be9e1aafa747c32151R23

**Comment by atwellpub** [comment]
Not until we refactor the data loading system to be inside a hook. 

I can begin the refactor after we clear this ACF conversion. 

BTW we are ready to test. All the templates have been converted and are in this feature branch:

https://github.com/inboundnow/landing-pages/tree/feature/Template_conversions_to_acf

**Comment by DavidWells** [comment]
I figured out the issue I was having with the feature branch.

If ACF pro plugin is activated the colorpicker setup here:
https://github.com/inboundnow/landing-pages/blob/feature/Template_conversions_to_acf/classes/class.acf-integration.php#L212-L216
never runs to fix the colorpicker output.

see: http://www.screencast.com/t/oXwYYy7T

**Comment by atwellpub** [comment]
Alright ready to pull and test again.

**Comment by DavidWells** [comment]
Looks like it works!
