### ISSUE TITLE
Broken demo link in Default template

### ISSUE THREAD

**Issue by daprela** [inboundnow/landing-pages#227]
The config.php file in the demo template has this link for the demo page
http://docs.inboundnow.com/landing-pages/dev/creating-templates/default-wp-themes
That link brings to a 404

I found these two links that could be the alternative
http://docs.inboundnow.com/guide/creating-landing-page-templates/
http://docs.inboundnow.com/guide/creating-landing-page-default-template/

Which one should we use?

**Comment by atwellpub** [comment]
I think the image heavy one is better:
http://docs.inboundnow.com/guide/creating-landing-page-default-template/
