### ISSUE TITLE
New ACF templates initiative. 

### ISSUE THREAD

**Issue by atwellpub** [inboundnow/landing-pages#228]
I've pulled in the ACF conversion templates branch into master. @DavidWells all the core templates are ready for another round of testing. 

@daprela will you report all issues you face with ACF and Landing Pages here? I noticed you mentioned that countdown lander ACF fields are not showing in the landing page edit area. Try pulling the latest master. It should clear up any UI issues. 

One thing to notice, when building these next templates we will be using repeater fields and that means  we'll need to have ACF Pro activated while deving. As we project now, as far as I have heard, any template that has a repeater will only be available to our membership holders and available for purchase to those who own ACF Pro separately and are not Inbound Membership holders. We aren't exactly sure how we are going to market them as stand alone products, or even if we will. 

For now the best way to dev these templates are to have Landing Page active, Inbound Pro deactive, and ACF Pro active. To use ACF Pro's field builder and David's helper tool to generate the index.php file.

If there are any issues with the config.php file or index.php file please list them here and I'll help hammer on them until we are all aware of the best standard. 

Cheers

**Comment by atwellpub** [comment]
To tell Landing Pages to hide UI elements:
https://github.com/inboundnow/landing-pages/blob/master/templates/svtle/config.php#L18

To tell landing pages to load the correct ACF fields, this will be the same on every template:
https://github.com/inboundnow/landing-pages/blob/master/templates/svtle/config.php#L292-L305

**Comment by daprela** [comment]
I think I finally got the problems of ACF fields not showing up. If I create a new landing page but not give it immediately a title I won't have any ACF fields in the editor. If I give a title to the landing page everything works. I've tested it with several templates and the behavior is consistent.

**Comment by daprela** [comment]
I'm having problems on all templates. They don't show up if I preview them. It doesn't change if they're draft or published. I've enabled WP_DEBUG, and I get this warning:
![warning-landing](https://cloud.githubusercontent.com/assets/6268698/9712302/ed7eb1c8-5573-11e5-9fe7-0563fe79e886.png)

Not sure if it is the cause. I'll configure the template, and then I'll try to track down the issue.

**Comment by daprela** [comment]
To be able to test and refine the template, I've moved the code into the mailer and I'm testing it as an email template. This allows me to test the editor interface and the template code.

**Comment by atwellpub** [comment]
@daprela Issue with ACF fields not loading is taken care of by making the Landing Page descriptive title required when first creating a landing page. More information in the attached issue above.

**Comment by atwellpub** [comment]
@daprela the issue attached above addresses the preview issue with Landing Pages (does not solve it though).

**Comment by daprela** [comment]
I pushed the new landing page template, that I named 'acacia'. It's far from finished but while I'm working on it there are issues arising, and I could need to involve you sometimes. Once this is finished and working the main issues should be fixed and the next templates easier to do

**Comment by DavidWells** [comment]
Hey @daprela where is the new template for me to checkout? Thanks

**Comment by atwellpub** [comment]
Closing this issue. We can create new issues for new templates.
