### ISSUE TITLE
Fatal error at landing pages activation

### ISSUE THREAD

**Issue by daprela** [inboundnow/landing-pages#232]
In trying to track the problem with the template previews not working, I've installed the latest Github version of landing-pages on my hosting server.
Unfortunately, when I tried to activate the plugin I got this error (notice that the previous version installed dated 18 August worked)

**Fatal error:** Call to undefined function inbound_get_parent_directory() in **/home/inboundtest/public_html/wp-content/plugins/landing-pages/templates/countdown-lander/config.php on line 11**

**Comment by atwellpub** [comment]
For the moment we've backed out of using the inbound_get_parent_directory function in favor for ```basename(dirname(__FILE__))```
