### ISSUE TITLE
Notice in landing pages for repeater fields

### ISSUE THREAD

**Issue by daprela** [inboundnow/landing-pages#234]
When WP_DEBUG is set to true a notice shows up when I preview a landing page. It looks like this notice is produced by the ACF integration for repeater fields when there isn't a repeater field in the group

![notice-landing](https://cloud.githubusercontent.com/assets/6268698/9737718/30e8bb94-5672-11e5-84dc-ed67ffc6f7a8.png)

**Comment by atwellpub** [comment]
https://github.com/inboundnow/landing-pages/commit/c35d5606c1bc7ff8daeeab959c54fd9d0b46c939
