### ISSUE TITLE
Problem with conditional logic in ACF fields

### ISSUE THREAD

**Issue by daprela** [inboundnow/landing-pages#237]
In the new Acacia template I'm using conditional logic to let the user decide wheter to add an image or video to the big hero box.
This conditional logic doesn't work correctly, and I believe that it could have to do with some integration problem.
The radio field 'Add Media' should choose between the two fields and let show up only the chosen one but if you choose video you cannot go back to image, and if you add an image it returns a false value inside the template. The image is stored correctly in the database from what I could verify.

**Comment by atwellpub** [comment]
I think the lastest round of commits solve this problem. I'm able to toggle between the two.
