### ISSUE TITLE
Image field returning 'false' in repeater field

### ISSUE THREAD

**Issue by daprela** [inboundnow/landing-pages#238]
This issue has come out while working on the Acacia template (#236 ). The testimonials section uses a repeater field, all the subfields give the correct value with the exception of the image field that returns false.
Please refer to this section of code:
https://github.com/inboundnow/landing-pages/blob/master/templates/acacia/index.php#L138-L195

This problem may be linked to the problem that I reported in Issue #237

**Comment by atwellpub** [comment]
There is an issue with return formatting between ACF4 (free) and ACF5(pro) that causes some issues. I told the code to ignore additional customizations for repeater fields. It's possible we'll see on issues where return formatting is required, enabled, and not inside a repeater field too.

**Comment by daprela** [comment]
Right now the problem is fixed ant the images show up
