### ISSUE TITLE
Template change not working and the flow needs to get changed

### ISSUE THREAD

**Issue by DavidWells** [inboundnow/landing-pages#245]
The new template change thing is not working.

http://wpdev.dev/wp-admin/post.php?post=119459&action=edit#

There is also a problem here from a UX side.

If the user changes there current template all options are going to get hose and they will need to start over. So why not remove this as an option and force the user to create a new variation with a new template?

So the user only has 2 options:

1. Clone existing version and edit it
2. Create new variation and choose from available templates

This way, no user will ever be surprised when the current template they spent time on vanishes. It won't be possible

**Comment by atwellpub** [comment]
Original Issue:
https://github.com/inboundnow/landing-pages/issues/235

Going to need some details on how it's not working. Looks like it is working over here. 

After a template change none of the old template settings get hosed. So if you change from a setup Simple Solid Lite template to a Half and Half template and then back to Simple Solid Lite the the old settings are still available.

**Comment by atwellpub** [comment]
Is this issue still open?
