### ISSUE TITLE
Acacia FAQ repeater row outputting an additonal empty FAQ section

### ISSUE THREAD

**Issue by DavidWells** [inboundnow/landing-pages#246]
The editor has 3 FAQ sections and the output has 4. See: http://www.screencast.com/t/t9M9j8YP

**Comment by daprela** [comment]
Yes, this is made on purpose. When the FAQ layout in on two columns, in case the FAQs are in odd number you need to add an empty box to make them even, or the button comes misaligned. I was looking for a better and simpler solution than this, I will keep experimenting

**Comment by DavidWells** [comment]
Aha I see. The editor was triggering the breakpoint so they were all inline.

We can probably just use CSS to add the new line instead of the extra
content

**Comment by daprela** [comment]
Problem solved, I got rid of the empty section and fixed the button alignment problem
