### ISSUE TITLE
[acf] Triumph

### ISSUE THREAD

**Issue by daprela** [inboundnow/landing-pages#248]
I've started working on the new template

**Comment by daprela** [comment]
I started adding the template. Right now there is only the header working with acf fields, the rest is plain html. It will be replaced with acf fields as I go on with the development.

As for the header, I plan further enhancements. The navigation links need different colors for active and hover statuses, which I'll have to calculate from the text color. I've already done something similar in the newsletter template in the mailer plugin for the border of the callout, and the result was excellent.

It seems there's an issue with the image field (#249)

**Comment by daprela** [comment]
I have added the inline hover colors. Since css doesn't allow to define status in inline styles, I have used javascript. In order to correctly calculate the hover color I have added a function to convert colors from hex to hsl. This allows for various and simple color manipulations like darkening or lightening colors, desaturate them etc. I would suggest to move this function into a shared common folder so that it can be easily used by any template

**Comment by DavidWells** [comment]
Yeah we needed some functions like this for some other premium templates. Collecting them and using for all templates is a good idea.

**Comment by atwellpub** [comment]
Having issue with http://# as default value (won't let me save). Not sure why it's working over there. Changing field type to 'text' and the default_value to '#'

**Comment by daprela** [comment]
The HexToHsl function is allowing me to create very cool effects. I've added the feature section, the text of the button changes on hover depending on the color assigned to it.
Also, I've added a small jquery function that allows to change the size of the video. As a Result, I've also added two fields in the edit to allow choosing width and height of the video in pixels. I've ported this to the Acacia template, and now the problem of the size of the video is definitely fixed.

**Comment by daprela** [comment]
The template is almost finished. We need to discuss a few details, like having or not wysiwyg fields in some boxes, as wysiwyg prevents from setting up the text color.

Please test and review the template

**Comment by atwellpub** [comment]
![](http://content.screencast.com/users/adbox/folders/Jing/media/0499761f-dee7-4737-8674-b608497e4cb9/2015-09-21_1335.png)


![](http://content.screencast.com/users/adbox/folders/Jing/media/19c99dc6-97cd-44c6-a1b4-98981bdafbd7/2015-09-21_1336.png)

Will you give more detail about the color issue with wysiwyg?

**Comment by atwellpub** [comment]
![](http://content.screencast.com/users/adbox/folders/Jing/media/79c2b7d6-5fcf-48be-9a6d-63caea582703/2015-09-21_1413.png)

**Comment by daprela** [comment]
The problem of color with wysiwyg is that if I enclose the wysiwyg into a div and set the color property for the div, that is not inherited by the wysiwyg. In theory it should be inherited but it's not

**Comment by atwellpub** [comment]
Can we repeat/test with the current setup?

**Comment by daprela** [comment]
>Can we repeat/test with the current setup?

In the centered content area, the main content is a wysiwyg
https://github.com/inboundnow/templates-landing-pages/blob/master/triumph/index.php#L385

**Comment by daprela** [comment]
I've reduced the logo height to a maximum of 30px. This should fix the problem

**Comment by daprela** [comment]
I don't know what you've done but after I downloaded the latest updates from git I'm getting this warnings when I preview my landing pages:

`Warning: strpos() expects parameter 1 to be string, array given in D:\Bitnami\wampstack-5.4.32-0\apps\inboundfree\htdocs\wp-includes\shortcodes.php on line 191`

` Warning: preg_match() expects parameter 2 to be string, array given in D:\Bitnami\wampstack-5.4.32-0\apps\inboundfree\htdocs\wp-includes\shortcodes.php on line 202`

From my debug:
https://github.com/inboundnow/landing-pages/blob/master/classes/class.acf-integration.php#L132
in one of the calls to the function Landing_Pages_ACF::load_value() the parameter $value is an array containing the names of all the flexible fields. The do_shortcode function doesn't work with arrays

**Comment by daprela** [comment]
I've made the button optional and added an optional header to the testimonials section

**Comment by atwellpub** [comment]
> The problem of color with wysiwyg is that if I enclose the wysiwyg into a div and set the color property for the div, that is not inherited by the wysiwyg. In theory it should be inherited but it's not

Discovered the issue is that child elements do not inhereit inline styling even if it's set to !important, and the p css rule in style.css was overwriting the parent div container rule. I removed a default font color for p and the paragraphs inherit the parent div inline styling now.
