### ISSUE TITLE
Dismiss notice about uploaded inbound templates in theme section

### ISSUE THREAD

**Issue by atwellpub** [inboundnow/landing-pages#253]
Can make this smaller or dismissble? 

![](http://content.screencast.com/users/adbox/folders/Jing/media/3d01ad8c-3f30-42df-8a8a-9125070be969/2015-09-22_1546.png)

**Comment by DavidWells** [comment]
yea it can. Have you heard a user complain about this?

I have noticed no support requests on this issue anymore, which is why it is in your face
