### ISSUE TITLE
Is the plugin counting visits the right way?

### ISSUE THREAD

**Issue by daprela** [inboundnow/landing-pages#255]
I've noticed lately that when I create a new landing page from an existing template and test it the system counts my views as visits. It's true that you can clear the stats but does it really make sense to count the views that you make when you are logged in as admin? If I want to test views and conversions I can use two browsers and use one to make visits as not logged in.
Counting also the admin can pollute the stats in my opinion

**Comment by atwellpub** [comment]
I agree. In the upcomming consolidated plugin we'll provide this as an option. 

![](http://content.screencast.com/users/adbox/folders/Jing/media/57d5abe9-1a43-4cc3-a320-ea6cda82398a/2015-09-24_1607.png)

We have a way to do it now but I'm not sure what it is.
