### ISSUE TITLE
If landing pages + advanced custom fields (free) activated

### ISSUE THREAD

**Issue by DavidWells** [inboundnow/landing-pages#264]
ons in /Users/davidwells/Dropbox/Sites/WP.dev/wp-content/plugins/advanced-custom-fields/core/api.php on line 987

Notice: Undefined index: options in /Users/davidwells/Dropbox/Sites/WP.dev/wp-content/plugins/advanced-custom-fields/core/api.php on line 987

Notice: Undefined index: options in /Users/davidwells/Dropbox/Sites/WP.dev/wp-content/plugins/advanced-custom-fields/core/api.php on line 987

Notice: Undefined index: options in /Users/davidwells/Dropbox/Sites/WP.dev/wp-content/plugins/advanced-custom-fields/core/api.php on line 987

Notice: Undefined index: options in /Users/davidwells/Dropbox/Sites/WP.dev/wp-content/plugins/advanced-custom-fields/core/api.php on line 987

Notice: Undefined index: options in /Users/davidwells/Dropbox/Sites/WP.dev/wp-content/plugins/advanced-custom-fields/core/api.php on line 987

Notice: Undefined index: options in /Users/davidwells/Dropbox/Sites/WP.dev/wp-content/plugins/advanced-custom-fields/core/api.php on line 987

Notice: Undefined index: options in /Users/davidwells/Dropbox/Sites/WP.dev/wp-content/plugins/advanced-custom-fields/core/api.php on line 987

Notice: Undefined index: options in /Users/davidwells/Dropbox/Sites/WP.dev/wp-content/plugins/advanced-custom-fields/core/api.php on line 987

Notice: Undefined index: options in /Users/davidwells/Dropbox/Sites/WP.dev/wp-content/plugins/advanced-custom-fields/core/api.php on line 987

Notice: Undefined index: options in /Users/davidwells/Dropbox/Sites/WP.dev/wp-content/plugins/advanced-custom-fields/core/api.php on line 987

Notice: Undefined index: options in /Users/davidwells/Dropbox/Sites/WP.dev/wp-content/plugins/advanced-custom-fields/core/api.php on line 987

Notice: Undefined index: options in /Users/davidwells/Dropbox/Sites/WP.dev/wp-content/plugins/advanced-custom-fields/core/api.php on line 987

**Comment by DavidWells** [comment]
http://www.screencast.com/t/0NY9GYRkIbFR

**Comment by atwellpub** [comment]
I think this is an issue where there are pro registed fields in a wp instance:
https://github.com/elliotcondon/acf/issues/435

I have it modded in our bootstrapped acf4, but if the normal acf4 is on I can't mod their code so I opened the issue above.

**Comment by DavidWells** [comment]
Nope happens when only ACF(free) and current landing pages is activated as well

**Comment by DavidWells** [comment]
We need to solve this or fork the acf (free) plugin to suite our needs for the free plugin

**Comment by atwellpub** [comment]
Ok these are shored up. 
Shared needs to be synced again before deployment. Will you do that for me?

**Comment by DavidWells** [comment]
I am still seeing errors http://www.screencast.com/t/AJDjIe6hdO with LP +
CTA latest + ACF free installed

**Comment by DavidWells** [comment]
It seems to only appear when premium templates are in the uploads folder
though

**Comment by DavidWells** [comment]
So this might be okay. Let me test a couple more things

**Comment by DavidWells** [comment]
There are 2 templates from https://github.com/inboundnow/templates-landing-pages templates that are causing this error to show on the landing page edit screen when ACF free is activated (and acf pro is not)

```
Notice: Undefined index: options in /Users/davidwells/Dropbox/Sites/SVN.dev/wp-content/plugins/advanced-custom-fields/core/api.php on line 987

Notice: Undefined index: options in /Users/davidwells/Dropbox/Sites/SVN.dev/wp-content/plugins/advanced-custom-fields/core/api.php on line 987

```

Are they making a call to something that we can wrap to fix it?

**Comment by atwellpub** [comment]
No I checked the hard code in ACF and there's nothing we can do. I have already sent Eliot a pull request to solve the issue. He says he might accept it.
