### ISSUE TITLE
Styling issue with creating new landing page

### ISSUE THREAD

**Issue by atwellpub** [inboundnow/landing-pages#265]
Seems to be a styling issue when adding a new landing page

![](http://content.screencast.com/users/adbox/folders/Jing/media/b7e9afa6-3a72-4652-bb70-1024c67a9f6f/2015-10-09_1831.png)

**Comment by DavidWells** [comment]
Not seeing it here with the latest.

Can you clear your cache. If problem still exists, inspect the 'currently
selected' box to see what css is not being applied

**Comment by atwellpub** [comment]
Looked like it was only happening when CTA was disabled. Added the missing CSS.
