### ISSUE TITLE
[acf] Ambrosia

### ISSUE THREAD

**Issue by daprela** [inboundnow/landing-pages#266]
I will add the new template shortly

**Comment by daprela** [comment]
I've just added the Ambrosia template. I think you'll love this, I've used all the techniques developed in the previous templates plus a couple new, and the result is an extremely flexible template.

I've run out of landing pages templates. @DavidWells if you don't give me some new templates to work on, starting from tomorrow I'll go back working on the email templates, unless you ask me to do something else.

**Comment by atwellpub** [comment]
Going to start setting one up now.

**Comment by atwellpub** [comment]
Hey I've started building this one up. It builds very smooth. These repeaters are awesome. 

Two things I wonder, and I can't tell cause I have not seen the original:

* is there going to be a header
* should this one have a conversion area for inbound form? I am not seeing one.

**Comment by daprela** [comment]
No, there isn't any header here. As for the conversion area, I've called it subscribe section, and it's a flexible field area. In fact, I should have called it conversion area, I'll change the name

**Comment by atwellpub** [comment]
Subscribe v conversion area. I like subscribe too. Only reason to go with conversion area is for standardization sake.

**Comment by atwellpub** [comment]
Looking over the conversion area at the moment and have some questions and maybe suggestions:
http://screencast.com/t/90JCJM3hzNEi

**Comment by daprela** [comment]
I tried to make the forms 100% when I first started styling them, and I wasn't really satisfied about it just because the wysiwyg editor allows you total freedom of adding content, and you never know what a user wants to do with it. It is a possible solution though, there is just one line of css to make it work correctly without messing up the form. Add this at the end of the style section in the template head, if it makes sense I will make the commit.

`#inbound-form-wrapper input:not(.checkbox-inbound-vertical) {
	width: 100%;
}`

**Comment by atwellpub** [comment]
I think full width looks great. 

The only other addition would be to control the %width of the form container. Or leave it to custom CSS, what do you think?


![](http://content.screencast.com/users/adbox/folders/Jing/media/0583e73a-619a-4ebd-9ecd-a14dae91927b/2015-10-22_1602.png)

**Comment by daprela** [comment]
Do you want to add an option to the user to control the width of the form? That would be confusing for non technical users. I'm sure that to many of them 100% would refer to the width of the screen, not the width of an obscure and invisible box at the center of the screen. We would be flooded by support tickets if we would add this option for inbound forms. I think it's better to leave it to custom CSS

**Comment by atwellpub** [comment]
Ok sounds good. Template rocks.
