### ISSUE TITLE
Are we going to setup any demo pages for the new templates?

### ISSUE THREAD

**Issue by daprela** [inboundnow/landing-pages#277]
Do you think that we need to create any demo pages for the new templates? I think that it should probably become part of the building procedure of a new premium template adding also a demo page in the inboundnow website. What do you think?

**Comment by DavidWells** [comment]
yeah they would go in demo.inboundnow.com

**Comment by atwellpub** [comment]
David do we have a push strategy to demo.inboundnow.com that you want to teach us to push the new templates up there? 

@daprela I've created you an admin account on demo.inboundnow.com

**Comment by atwellpub** [comment]
* [ ] Install ACF Pro on demo.inboundnow.com
* [ ] Acacia
* [ ] Ambrosia
* [ ] Pure
* [ ] Triumph

**Comment by daprela** [comment]
The plugin ACF Pro is not yet installed on demo.inboundnow.com. I don't have the latest version, can you do it?

**Comment by atwellpub** [comment]
We are going to continue this issue from 
https://github.com/inboundnow/templates-landing-pages/issues/13#issuecomment-152197266
