### ISSUE TITLE
[acf] Gourmet

### ISSUE THREAD

**Issue by daprela** [inboundnow/landing-pages#279]
Gourmet is the name that I will give to the new restaurant template. I should be able to release it in a few days, it's beautiful and very complex.

**Comment by DavidWells** [comment]
nice name =)

**Comment by daprela** [comment]
I have added the Gourmet template.
As I said previously, it's beautiful and very complex. It took twice the time of a normal plugin doing this. It is my opinion that we should also think about the sale price of this template. It's a very special niche template, and it should be sold at a higher price.

There's still a lot to refine and adjust but the structure works and can be tested. Please give it a try and let me know your opinion

**Comment by atwellpub** [comment]
A couple of pricing cocepts:

1 site: 43 or 56
5 sites: (43 x 5) x.7 = 150
             (56 X 5) x .7 = 196
or
             (43 x 5) x.5 = 107.5
             (56 X 5) x .5 = 140
Unlimited sites:
             (43 x 10) x.5 = 215
             (56 X 10) x .5 = 280
or
             (43 x 10) x.3 = 29
             (56 X 10) x .3 = 168

I may be a cheapo, but I like the X , (X*5)*.5), (X*10)*.3 Where x = 56, or 53.

**Comment by DavidWells** [comment]
+1. Lets continue this thread on private repo. https://github.com/inboundnow/templates-landing-pages or in pro.

**Comment by daprela** [comment]
The template is ready for a test drive. I still had to work quite a bit on it to make it work properly but I think that now it's almost ready to be released.

Please give it a try

**Comment by atwellpub** [comment]
Gourmet is looking good!

So far:
Notice: Undefined variable: feature_area_image in F:\Dropbox\Websites\local\htdocs\inboundsoon\wp-content\uploads\landing-pages\templates\gourmet\index.php on line 494

**Comment by daprela** [comment]
Thank you for pointing this out, it was a copy/paste type of error :smile:

**Comment by atwellpub** [comment]
Template is looking great! Very awesome template.


![](filesystem:chrome-extension://fdpohaocaechififmbbbbbknoalclacl/temporary/screencapture-inboundsoon-dev-go-gourmet-1448999911526.png)
