### ISSUE TITLE
[doc] How To Install Premium Landing Page Templates For InboundNow

### ISSUE THREAD

**Issue by daprela** [inboundnow/landing-pages#280]
@atwellpub 
@DavidWells 
I have added the guide for installing premium Landing Pages templates. Please read it and add your comments for improving it

https://github.com/inboundnow/cta/blob/develop/shared/docs/install-premium-landing-page-templates.md

**Comment by atwellpub** [comment]
Looks great! I added some touches. Feel free to change them again. 

I also added the link to the documentation on one of the premium templates to see how it looks:
http://www.inboundnow.com/market/shift-landing-page-template/

This is just a temp note until we get the new site up and can get doc links into widget boxes.
