### ISSUE TITLE
[acf] Daffodil

### ISSUE THREAD

**Issue by daprela** [inboundnow/landing-pages#282]
New landing page based on template 11 already in an advanced phase. If there aren't unexpected issues it should be ready by next Tuesday.

**Comment by daprela** [comment]
Template added. It still need a few tests but it's working. Please test it and let me know

**Comment by daprela** [comment]
I think that there's something to discuss regarding this template.
This template has a header with a video that shows up in a light box. For the video to work you need to add the url that Youtube/Vimeo/Anyone else gives for embedding the video, but not the whole embed code, only the url. It's not complicated once you know it but the procedure needs to be explained, and the ACF interface doesn't allow to do much. I'd need to add some pictures showing where to click and what to copy but as far as I know it's not possible. The alternative would be a help page in the website. The field explanation text would link to that page.
What do you think?

**Comment by atwellpub** [comment]
is there not a tooltip/description where instructions can go?

**Comment by daprela** [comment]
The field description allows some html but it's rather limited. It's possible to add images but only by manually editing the config.php file, and not through the ACF editor which means that if you modify any fields and export them again you will lose the modifications.
I've rewritten the instructions for the header video field, please look at them this is the best that can be done.
Tooltips are not available unfortunately

**Comment by atwellpub** [comment]
I checked the instructions and the instructions are good. It's a shame we have to use the embed URL instead of a regular URL.  We'd have to get into regex parsing maybe to lift the video ids off.

This error is breaking my testing:

`
background: rgba(0, 0, 0, 0) url('<br />
<b>Notice</b>:  Array to string conversion in <b>F:\Dropbox\Websites\local\htdocs\inboundsoon\wp-content\uploads\landing-pages\templates\daffodil\index.php</b> on line <b>378</b><br />
Array') no-repeat center top ;
`

**Comment by daprela** [comment]
I have tried to use the normal url but unfortunately the lightbox is completely blank. It works only with the embed url.

I only had tested the template with default images, so didn't get that yet.
I left the default return value for the image field to an array instead of a url. Now I'm going to test edge cases to remove any possible bugs from the template

**Comment by daprela** [comment]
I think I've weed out most of the bugs in this template. Please test it again, something may be still missing.
There is a misalignment in the horizontal inbound form between the input field and the submit button. Just a couple of pixels but it's noticeable, and I've not been able to fix it. I will look into the forms module to see if it can be fixed from there

**Comment by daprela** [comment]
I've also added a tabbed interface. I like it more than the previous one and in my opinion it's less crowded. We'd need to make a user test to understand which is better

**Comment by atwellpub** [comment]
Tabs look excellent. Much better.

**Comment by atwellpub** [comment]
For some reason in the visual editor it's throwing up a bad request:

http://screencast.com/t/d7q8bx23Uzz

But looking good in the main preview page:
![dafodile](https://cloud.githubusercontent.com/assets/2002207/11571805/ce1e259a-99c3-11e5-80e9-0571141c2e97.png)


Could we change the footer's conversion area .sep css rule to have 94px top padding instead of 250px?

**Comment by atwellpub** [comment]
One last thing is it does not look like the promotion font awesome icons are showing up for any except the first.

**Comment by daprela** [comment]
Regarding the fontawesome icons I've noticed that some icons don't show up. I have no idea why, it seems that they are broken. This doesn't happen just in this template or with Inbound templates, I've had this problem also with other tools. Try to use the book icon in all the promotion boxes. If you used that icon already, then I have no idea, in my local install it works perfectly. Can you please check with the dev tools if the icon class is there?

**Comment by daprela** [comment]
> Could we change the footer's conversion area .sep css rule to have 94px top padding instead of 250px?
I've reduced the padding top to 94px and also the min height to 500px. With the horizontal form now it looks much better

**Comment by daprela** [comment]
I don't know what's the problem with the visual editor, it looks like it could be the JS library.
@DavidWells do you have any clues about this error?

**Comment by daprela** [comment]
I also prefer the editor with the tabs. The body section is still crowded because we can't use tabs there but at least you can close the flexible fields boxes.

If you both agree I can work on adding tabs also to previous templates, please let me know

**Comment by atwellpub** [comment]
You've my vote to go tabs. @DavidWells?

**Comment by atwellpub** [comment]
@daprela 

Not sure what's happened but it seems like an asset has disappeared from the repo:
http://screencast.com/t/7QFjips24US4

**Comment by daprela** [comment]
Sorry, that library is not used, it was enqueued by mistake, I've removed it
