### ISSUE TITLE
[acf] Ginger

### ISSUE THREAD

**Issue by daprela** [inboundnow/landing-pages#284]
New template under construction. This was numbered 16 on the list

**Comment by daprela** [comment]
@DavidWells this is the last template that I have, can you send me please a few more?

**Comment by daprela** [comment]
Ginger template ready, when you have time please give it a look and let me know what you think

**Comment by atwellpub** [comment]
Feature Area -> Title color is a text box instead of a color picker.

**Comment by atwellpub** [comment]
Looking good! Great work. Flexible/powerful template. 

![screencapture-inboundsoon-dev-go-ginger-landing-page-1450904945913](https://cloud.githubusercontent.com/assets/2002207/11985119/36732adc-a987-11e5-8d22-f022eae140dc.png)

**Comment by daprela** [comment]
Fixed feature area title along with another small issue with the form field.
To take screenshots of long pages I suggest the plugin Awesome Screenshot for both Chrome and Firefox
