### ISSUE TITLE
ACF Pro issue with repeater fields

### ISSUE THREAD

**Issue by atwellpub** [inboundnow/landing-pages#287]
Ran into a strange issue where our current setup did not work well with a template created by a 3rd party. I was able to fix it (possibly temporarily) for the customer issue. I am not understanding 100% why it was required.

**Comment by atwellpub** [comment]
https://github.com/inboundnow/landing-pages/blob/develop/classes/class.acf-integration.php#L308-L311

**Comment by daprela** [comment]
Have you verified if the template uses the repeater in a 'standard' way? Maybe it is a way of using it that you didn't anticipate and  that creates this issue, like, for example, many levels of nested repeater fields. It's just a guess, I thought that in my templates I had used it in pretty much all of the possible ways but I could be wrong

**Comment by atwellpub** [comment]
I'm just not sure, Giulio. I had to make updates again today to get Ginger to quite a bunch of soft errors. Commit above.
