### ISSUE TITLE
[acf] Event

### ISSUE THREAD

**Issue by daprela** [inboundnow/landing-pages#289]
This is a new specialty template for events (seminars, conferences, WordCamps) based on theme 19

**Comment by daprela** [comment]
Finished developing the template. Tomorrow I will make extensive testing.
It's a beautiful template. There are eight flexible areas plus an optional Google maps section that sits above the footer.
Please give it a look.

**Comment by atwellpub** [comment]
Looking over it now. I'll help by posting anything out of place I might come across.

* http://screencast.com/t/ESP8cIjFy Map seems to be required but I can't find the area to setup the map.
* spacing issue with topics: http://screencast.com/t/95c0dR0Dg7

Look great! Love it.

**Comment by daprela** [comment]
It looks like you have downloaded an older version of the template. Are you sure that you have the latest? The missing API key error was there before I added the maps section as part of the original template code, and also the spacing problems are fixed. The problems that you are reporting are all things that I've fixed or added yesterday, including the form shortcode in the conversion area.
Try to force a pull on Source Tree even if you don't see anything new. Sometimes Source Tree is slow at detecting new pushes.

As for the anchors, I should generate unique IDs for the sections so that they can be addressed. I don't do it right now but I could, it's not such a big change. The problem here is that only an advanced user will be able to make these links. You have to build the whole page first, and then analyze the source code with Firebug or the dev tools to look the IDs of each section. I cannot use static IDs because for example if you have a pricing flexible area and I give it the id="pricing", and then you add two of these areas to the template, the ID won't be unique anymore. So, I must count the areas and add a number to make the id unique, like id="pricing-1", id="pricing-2" etc.

**Comment by daprela** [comment]
Please test the template again. I've added unique IDs, plus now for all the sections that have more boxes inside I manage all the cases for one or more boxes. For example, the case of a 1 day conference (instead of two or more), with one speaker only etc.

If you don't find any issues I'll add the template to Bitbucket.

Should I also create the demo page, or I'll leave that to you?

**Comment by atwellpub** [comment]
I did have an older version, my apologies. 

Yes please flesh the demo page. 

Checking now.

**Comment by atwellpub** [comment]
This template looks awesome. Good job. 

![screencapture-inboundsoon-dev-go-event-1452707766074](https://cloud.githubusercontent.com/assets/2002207/12302786/aba85154-b9ec-11e5-8232-571e6c32fe58.png)

**Comment by daprela** [comment]
Ok, done, I've updated the page with the list of the templates, created the Bitbucket repo, and the demo page. Please check them out

**Comment by atwellpub** [comment]
Demo page looks great!
