### ISSUE TITLE
[acf] Iris

### ISSUE THREAD

**Issue by daprela** [inboundnow/landing-pages#300]
New template based on Theme 13

**Comment by daprela** [comment]
The template is finished. Need some more testing but you can download it and try it.
Tomorrow I'll finish testing and create demo page and repo on Bitbucket

**Comment by daprela** [comment]
Template finished, found no further issues

**Comment by daprela** [comment]
Demo page here
http://demo.inboundnow.com/go/iris/

**Comment by atwellpub** [comment]
Looks great! 

![screencapture-demo-inboundnow-com-go-iris-1454621488081](https://cloud.githubusercontent.com/assets/2002207/12830382/9bbc4f4c-cb54-11e5-9e3f-962d98437c01.png)

Commentary on demo site:
http://screencast.com/t/wrP4tzCUIo

**Comment by atwellpub** [comment]
Accidentally built another one. Love it! 

![screencapture-inboundsoon-dev-go-iris-1455582097832](https://cloud.githubusercontent.com/assets/2002207/13063830/dc470ec4-d411-11e5-85fd-7a6f81f965d9.png)
