### ISSUE TITLE
[acf] Jasmine

### ISSUE THREAD

**Issue by daprela** [inboundnow/landing-pages#302]
New template based on theme 17

**Comment by daprela** [comment]
The template is finished. Needs just some more testing for edge cases.

Please test it and let me know

**Comment by daprela** [comment]
Template finished. Now I'm going to start the next one

**Comment by atwellpub** [comment]
In testing I've found:

Featured section -> background image is a text field instead of a image upload field.

**Comment by daprela** [comment]
I missed the featured section background image issue but everything else should be fixed. I tried to upload a new fixed version of the template yesterday, and don't understand why it didn't fix all the issues. I made a css adjustment that I have in my local install, and it's also in the Bitbucket repo but when I upload the new version of the template it disappears. It's driving me crazy

**Comment by daprela** [comment]
And yes, the featured image is meant to sit on the bottom without any padding or margin

**Comment by daprela** [comment]
Wait, when have you downloaded the template? I see bugs in the template that I've fixed a couple of days ago. The only bug that I missed is the image in the creators section, which is strange anyway because it's set to be a circle.
Still trying to figure out the problem in the demo website. I think that I will uninstall the template and re-upload it

**Comment by atwellpub** [comment]
Hey Giulio I believe you. After I had tested the page I opened sourcetree and discovered I had not completed the pull confirmation dialog. Sorry about that I'll do better on making sure I'm 100% updated before testing.
