### ISSUE TITLE
[acf] Ginseng

### ISSUE THREAD

**Issue by daprela** [inboundnow/landing-pages#304]
New template based on theme 15

**Comment by daprela** [comment]
Been struggling a lot today with the JS of this template. I'ts nothing fancy, it just didn't work, the same code that in the static template works in WordPress stops working. At the end, I had to eliminate a nice fading effect

**Comment by daprela** [comment]
The template is finished. It has been unexpectedly difficult to make this template work. A lot of issues from JavaScript, in one case I had to remove the function because I haven't been able to find why it didn't work while in the static file it worked.

There is still a problem, this also very strange. The button of the inbound form comes two times higher than normal. This is strange, I've been using the exact same css to render these forms across all templates without any problems. I tried to load the template without any JavaScript and CSS enqueued, and still the button is two times higher than normal. I don't know where this height is set, all the other templates still work and render a normal button, and use the same shortcode, so why this one doesn't?

@atwellpub If you have a few minutes please look into it, it's driving me crazy, and I've lost hours trying to troubleshoot this damn template

**Comment by atwellpub** [comment]
It looks like a line break (<br>)  is being added in above the submit button text. Looking into it.

**Comment by atwellpub** [comment]
Turns out the line break issue with the submit form was due to a \r\n return in our share class.form.php file being interpreted by WordPress's wpautop as a line break. Should be gone soon.

**Comment by daprela** [comment]
That's really strange, why the problem shows up only in this template and not in the others then? What's different here?

**Comment by atwellpub** [comment]
No clue atm

**Comment by daprela** [comment]
Not sure what happened, you pushed something and now I have a folder called 'ginseng-landing-page-template' with the ginseng folder inside it, which of course doesn't work. The original ginseng folder is still there.
I'd delete this new folder but I want to know your opinion before because this is coming from your modification

**Comment by daprela** [comment]
I just noticed that I also have a jasmine-landing-page-template folder in addition to the ginseng

**Comment by atwellpub** [comment]
They are accidents. To be honest Giulio I'm being so demolished from customer support and debugging efforts that I have no idea why they are there. 

After we get all the premium landers up we have to revisit expanding our quality control tests. I'm not sure what is more important:

* 100% translation
* Adding more templates 
* Assurance testing safety net.

**Comment by daprela** [comment]
No problem, I will delete them.

Let's move this conversation to the private inboundnow.com repo.
