### ISSUE TITLE
[acf] publisher-1

### ISSUE THREAD

**Issue by daprela** [inboundnow/landing-pages#310]
New template for e-books based on theme 6

**Comment by atwellpub** [comment]
Excited about this one. 

I have a fun idea for us. We should both make a niche landing page and submit it to codecanyon to work with the free version of Landing Pages. At your leisure, off the books. I'll do the same and just get it up when I can. 

But I think ebooks are going to be a good seller. Huge self publishing community out there and it will bring in authors, who are really interesting folk.

**Comment by daprela** [comment]
We have two ebook templates to convert right now. It would be good to make more but they'll have to be designed from scratch.
Making a landing page for the free version means no repeater and no flexible fields, right? I don't feel I'm a good designer, I'll see what I can do :smile:

**Comment by DavidWells** [comment]
If you guys are looking for additional designs

See the work of http://n33.co/

A lot of his stuff is open source Creative Commons 

He runs https://carrd.co/ and perhaps he'd be willing to sell those designs as well



- David Wells

**Comment by daprela** [comment]
The template is finished, please give it a try and let me know if you like it :smile:

**Comment by atwellpub** [comment]
Looks real good woo! 

I'm having trouble with the slideshow images breaking through, are you?

**Comment by daprela** [comment]
Sorry, I just noticed a configuration problem with the image field. It's fixed now. I still have to complete the tests to check colors and responsiveness

**Comment by daprela** [comment]
The template should be ok, I haven't found any other problems so far.

http://demo.inboundnow.com/go/publisher-1/
https://www.inboundnow.com/market/publisher-1/
