### ISSUE TITLE
All P tags are missing from copy

### ISSUE THREAD

**Issue by lordmatt** [inboundnow/landing-pages#318]
For some reason, the copy from the landing page custom post type is not being passed through the smart paragraphs converter and there are no P tags except the ones I force in which is hard work as the WYSIWYG editor strips them out again.

Landing pages was installed from WordPress.org today.

**Comment by lordmatt** [comment]
I should add this is with the default theme template which I assume does not use the `wpautop()` function.

**Comment by atwellpub** [comment]
The default template does source from the theme's single.php file. Which means if there's a problem with wpautop on the landing page custom post type there should, in theory, be one on blog posts as well. 

You can skip usage of single.php by creating a single-landing-page.php file and ensuring wpautop() is in place. See:

http://docs.inboundnow.com/guide/default-wp-themes/
and
https://codex.wordpress.org/Function_Reference/wpautop

**Comment by lordmatt** [comment]
I understand. Thank you for that.

**Comment by atwellpub** [comment]
Heya I also discovered you were right and updated the files. Fix is in. Thank you.
