### ISSUE TITLE
[Feature Request] Featured image on landing pages

### ISSUE THREAD

**Issue by lordmatt** [inboundnow/landing-pages#319]
Is there any chance of adding featured images to landing pages?

I am hoping to promote my three key landing pages from the front page of my site and the theme relies heavily on featured images to differentiate the offerings.

**Comment by atwellpub** [comment]
Added in dev. Will be available next release. 

It's setup so that if you would like to turn features images on then we can in the settings area. Featured images enabled by default would confused green users.

**Comment by lordmatt** [comment]
That's wonderful. Thank you very much.
