### ISSUE TITLE
Standardize CTA/Landing Page template function

### ISSUE THREAD

**Issue by DavidWells** [inboundnow/landing-pages#46]
Merge wp_cta_get_parent_directory and lp_get_parent_directory functions as well as other non shared functions

**Comment by atwellpub** [comment]
Hey we will need legacy support for lp_get_parent_directory for custom templates and premium templates. 

I notice this is an old issue. We ignored it right?

**Comment by atwellpub** [comment]
Now being tracked here: https://github.com/inboundnow/landing-pages/issues/220

**Comment by DavidWells** [comment]
legacy functions are fine but we need a standardized shared one like I
reference in #220

This way all templates use the same 'things' and are easier to build
