### ISSUE TITLE
Exclude IPS from tracking

### ISSUE THREAD

**Issue by DavidWells** [inboundnow/landing-pages#48]
http://www.inboundnow.com/support/topic/not-including-logged-in-usersips-from-landing-page-stats/

**Comment by atwellpub** [comment]
This is now available as an Inbound Pro feature:
![](http://content.screencast.com/users/adbox/folders/Jing/media/47b39438-cf9f-43c9-b985-61a7cb7b1bb8/2015-10-29_1559.png)
