### ISSUE TITLE
Conversion Pixel

### ISSUE THREAD

**Issue by aikar** [inboundnow/landing-pages#85]
See https://github.com/inboundnow/cta/issues/75#issuecomment-70010580 for additional implementation instructions. 

-------

I have special needs when it comes to considering a conversion, and would require the use of a conversion pixel to fire on another page/event to mark a conversion, and not a simple form submission.

Can you add support for this?

Also supporting multiple conversion types would be excellent.

**Comment by atwellpub** [comment]
See: https://github.com/inboundnow/cta/issues/75#issuecomment-70010580 for more information..

**Comment by atwellpub** [comment]
https://github.com/inboundnow/landing-pages/commit/06b365d2c9c6cb680683cb084a8588121571b382

**Comment by atwellpub** [comment]
![](http://content.screencast.com/users/adbox/folders/Jing/media/e734014a-2e37-4ff0-b326-83a589011330/2015-10-29_1551.png)
