### ISSUE TITLE
Add File upload to form

### ISSUE THREAD

**Issue by DavidWells** [inboundnow/landing-pages#87]
>>We have people send us requests to pick up their furniture from their homes and bring it to our stores to sell. Often times, they want to be able to share pictures of the merchandise prior to pick-up to determine approx pricing. It would be cool if we could have a field in the forms where customers could attach pictures or documents to share with us. Another thought that would be cool is if there was a way to reply to a lead with a personalized response.

**Comment by cvillemure** [comment]
I would love a feature like that too, to be able to receive Presentation letter and Curriculum Vitae

**Comment by DavidWells** [comment]
This example should point us in the right direction: https://github.com/mikejolley/WP-Job-Manager/commit/dcad12bcd0fe20b378cfc274ba5cd04a10390f1f

**Comment by kiritDholakiya** [comment]
Thanks for reference of mikejolley site. I working on it. give you update once this implemented in plugin... :)

**Comment by atwellpub** [comment]
Another user has asked for this and provided insight:
http://support.inboundnow.com/support/topic/attachment-for-forms/#post-114459

* On Email Notification Should Provide Links to Attached Files

**Comment by atwellpub** [comment]
Attachments uploaded by users should be uploaded into:

/wp-content/uploads/leads/attachments/LEAD-ID/

**Comment by atwellpub** [comment]
This commit: https://github.com/inboundnow/cta/commit/6379e1891b055c8b30f76410cfe3dd87d9395062

Adds a hook that will allow a custom field type.

**Comment by atwellpub** [comment]
This extension has been developed.

http://www.inboundnow.com/market/inbound-attachments/
